// ============================================================
// Drift — Shared TypeScript Types
// ============================================================

export type ContentType =
  | 'academic'
  | 'political'
  | 'health'
  | 'tech'
  | 'news'
  | 'legal'
  | 'financial'
  | 'entertainment';

export type DistortionMode =
  | 'confidence-inflation'
  | 'detail-loss'
  | 'framing-shift'
  | 'context-stripping'
  | 'fabrication';

export type AttentionSpan = 'full' | 'skim' | 'headline-only';

export type FidelitySlope =
  | 'steep'
  | 'gradual'
  | 'cliff'
  | 'plateau-then-drop';

export type TextSegmentFate =
  | 'survived'
  | 'paraphrased'
  | 'lost'
  | 'fabricated';

export type ActiveView = 'river' | 'timeline' | 'damage';

// ── Persona ──────────────────────────────────────────────────
/**
 * Represents a single node in the information chain.
 * Each persona transforms content based on its unique biases and incentives.
 */
export interface PersonaSpec {
  /** Uniquely identifies this persona in the specific chain */
  id: string;
  /** Human-readable display name, e.g., "Science Journalist" */
  name: string;
  /** Contextual role description, e.g., "Writes for a mid-tier publication" */
  role: string;
  /** Platform where content is published, influencing format and tone */
  platform: string;
  /** Behavioral tendencies applied during transformation */
  biases: string[];
  /** Expected depth of engagement with previous content */
  attentionSpan: AttentionSpan;
  /** Primary motivation for sharing, e.g., "maximize clicks" */
  incentive: string;
  /** Specific instructions on how the persona alters the text */
  transformationStyle: string;
}

// ── Chain Spec (output of Content Analyzer) ──────────────────
/**
 * Configuration that dictates the sequential flow of personas.
 * Generated by the Content Analyzer based on the source text.
 */
export interface ChainSpec {
  /** Categorization of the source material */
  contentType: ContentType;
  /** Brief 1-sentence summary of the original source */
  contentSummary: string;
  /** The expected primary way the information will degrade */
  primaryDistortionMode: DistortionMode;
  /** Number of personas in the chain (valid range: 3-7) */
  chainDepth: number;
  /** Sequence of personas that will process the content sequentially */
  personas: PersonaSpec[];
  /** Expected shape of the fidelity curve across nodes */
  expectedFidelitySlope: FidelitySlope;
  /** How susceptible this text is to distortion (range: 0-100) */
  vulnerabilityScore: number; // 0–100
  /** Specific facts to trace through the network (exactly 3-5 items) */
  keyClaimsToTrack: string[]; // 3–5 specific trackable facts
}

// ── Node Output (one cascade step) ───────────────────────────
/**
 * Output from a single step in the multi-LLM cascade.
 */
export interface NodeOutput {
  /** Matches the id of the corresponding PersonaSpec */
  personaId: string;
  /** Matches the name of the corresponding PersonaSpec */
  personaName: string;
  /** Matches the role of the corresponding PersonaSpec */
  personaRole: string;
  /** The text after it was processed by the persona's transformation prompt */
  transformedText: string;
  /** Size of the output for API budgeting/monitoring */
  tokenCount: number;
}

// ── Metrics (computed after each node) ───────────────────────
/**
 * Quantitative and qualitative measurements of fidelity and distortion
 * calculated after each node processes the content.
 */
export interface NodeMetrics {
  /** The 0-based position of this node in the sequence */
  nodeIndex: number;
  /** Identifier of the persona that generated this output */
  personaId: string;

  // Core scores
  /** Semantic similarity to the original source text (range: 0-100) */
  fidelityScore: number;        // 0–100
  /** Degree to which cautious claims became definitive assertions (range: 0-100) */
  confidenceInflation: number;  // 0–100
  /** Percentage of trackable claims that remain intact (range: 0-100) */
  detailSurvivalRate: number;   // 0–100
  /** Sentiment shift: -100 (alarmed/negative) to +100 (charged/positive), 0 neutral */
  framingPolarity: number;      // -100 to +100

  // Deltas vs previous node
  /** Change in fidelity compared to the prior step (range: -100 to 100) */
  fidelityDelta: number;
  /** Change in inflation compared to the prior step (range: -100 to 100) */
  confidenceInflationDelta: number;
  /** Change in survival rate compared to the prior step (range: -100 to 100) */
  detailSurvivalDelta: number;
  /** Change in framing compared to the prior step (range: -200 to 200) */
  framingPolarityDelta: number;

  // Claim tracking
  /** Tracked statements that have persisted unchanged */
  survivingClaims: string[];
  /** Tracked statements missing from this node's output */
  lostClaims: string[];
  /** Tracked statements whose meaning was significantly warped */
  distortedClaims: string[];
  /** Completely novel or hallucinated claims not in the original text */
  addedClaims: string[]; // fabricated / inferred — not in original

  // Qualitative summary
  /** One-sentence description of the most prominent distortion in this step */
  primaryDistortionObserved: string;
}

// ── Damage Report Segment ─────────────────────────────────────
/**
 * Detailed analysis of what happened to a specific chunk of original text.
 */
export interface TextSegment {
  /** The original substring being analyzed */
  text: string;
  /** Assessment of what happened to this text over the cascade */
  fate: TextSegmentFate;
  /** Array of node indices where this segment was preserved */
  appearsInNodeIndices: number[];
}

// ── Full Cascade Result ───────────────────────────────────────
/**
 * Complete record of a single Drift run, capturing the full state and history.
 */
export interface CascadeResult {
  /** UUID representing this particular execution run */
  sessionId: string;
  /** The root content that initialized the cascade */
  source: string;
  /** The configuration controlling this cascade run */
  chainSpec: ChainSpec;
  /** Ordered list of every transformation step */
  nodes: NodeOutput[];
  /** Ordered list of the calculated metrics for each step */
  metrics: NodeMetrics[];
  /** Optional token-level breakdown of information loss over time */
  damageSegments?: TextSegment[];
  /** Cross-node variance indicator measuring disagreement across nodes (range: 0-100) */
  disagreementScore: number; // 0–100
  /** ISO timestamp representing when this cascade completed */
  computedAt: string; // ISO timestamp
}

// ── Streaming Event ───────────────────────────────────────────
/**
 * Represents a discrete event emitted during a running cascade stream.
 */
export type StreamEvent =
  | { type: 'chain-ready'; chainSpec: ChainSpec }
  | { type: 'node-complete'; nodeIndex: number; node: NodeOutput; metrics: NodeMetrics }
  | { type: 'cascade-complete'; result: CascadeResult }
  | { type: 'error'; message: string };

// ── App State ─────────────────────────────────────────────────
/**
 * State phases of the frontend client.
 */
export type AppPhase =
  | 'idle'
  | 'fetching-url'
  | 'analyzing'
  | 'chain-preview'
  | 'cascading'
  | 'complete'
  | 'error';

/**
 * Comprehensive application state for the client-side UI.
 */
export interface AppState {
  /** Current progress phase within the interactive analysis flow */
  phase: AppPhase;
  /** The active cascade session id while a run is in progress or completed */
  sessionId: string | null;
  /** User-provided raw text data */
  inputText: string;
  /** User-provided URL before extraction */
  inputUrl: string;
  /** The generated configuration, if analysis has succeeded */
  chainSpec: ChainSpec | null;
  /** Current execution progress (range: 0-100) */
  cascadeProgress: number; // 0–100
  /** In-flight outputs as nodes complete sequentially */
  partialNodes: NodeOutput[];
  /** In-flight metric scores as nodes complete sequentially */
  partialMetrics: NodeMetrics[];
  /** The complete end result, populated only after full cascade completion */
  result: CascadeResult | null;
  /** Error message to display if any step failed */
  error: string | null;
  /** Controls which visualization panel is currently rendered */
  activeView: ActiveView;
}
